const fs = require("node:fs");
const marker = "<!-- mergeproof-comment -->";
const risks = [["Authentication", /(auth|login|session|oauth|jwt|password)/i], ["Permissions", /(permission|role|rbac|acl|authorize)/i], ["Payments", /(payment|invoice|billing|stripe|checkout|webhook)/i], ["Database", /(migration|schema|database|sql)/i], ["Environment", /(\\.env|environment|config|secret|credential|token)/i]];
const terms = (s) => s.toLowerCase().replace(/[^a-z0-9\\s]/g, " ").split(/\\s+/).filter((w) => w.length > 2);
const isTest = (name) => /(^|\\/)(__tests__\\/|test\\/|tests\\/)|\\.(test|spec)\\.[^.]+$/i.test(name);
function criteria(body = "") { const section = body.match(/#{1,6}\\s*acceptance criteria\\s*\\n([\\s\\S]*?)(?=\\n#{1,6}\\s|$)/i); return section ? section[1].split("\\n").map((line) => line.match(/^\\s*-\\s*\\[[ xX]\\]\\s+(.+)$/)).filter(Boolean).map((m) => m[1].trim()) : []; }
function matches(criterion, files, test) { const wanted = new Set(terms(criterion)); return files.filter((f) => isTest(f.filename) === test).map((f) => ({ name: f.filename, score: terms(f.filename).filter((w) => wanted.has(w)).length })).filter((f) => f.score).sort((a,b) => b.score-a.score).slice(0,2).map((f) => f.name); }
function brief(items, files) {
  if (!items.length) return marker + "\\n## MergeProof — Evidence Gate\\n\\n**Needs spec:** add an \`## Acceptance criteria\` section with Markdown checkboxes.";
  const rows = items.map((criterion) => { const implementation = matches(criterion, files, false), tests = matches(criterion, files, true), verdict = !implementation.length ? "Unproven" : !tests.length ? "Needs test" : "Proven"; const list = (xs) => xs.length ? xs.map((x) => "\\`" + x + "\\`").join("<br>") : "—"; return { criterion, verdict, line: "| " + criterion.replace(/\\|/g, "\\\\|") + " | " + list(implementation) + " | " + list(tests) + " | **" + verdict + "** |" }; });
  const flags = risks.filter(([,p]) => files.some((f) => p.test(f.filename))).map(([name]) => name + " path changed"); if (files.some((f) => !isTest(f.filename)) && !files.some((f) => isTest(f.filename))) flags.push("Application code changed without a changed test file");
  const focus = rows.filter((r) => r.verdict !== "Proven").map((r,i) => (i+1) + ". Verify: " + r.criterion);
  return marker + "\\n## MergeProof — Evidence Gate\\n\\n| Acceptance criterion | Implementation evidence | Test evidence | Verdict |\\n| --- | --- | --- | --- |\\n" + rows.map((r) => r.line).join("\\n") + (flags.length ? "\\n\\n### Risk flags\\n" + flags.map((f) => "- " + f).join("\\n") : "") + (focus.length ? "\\n\\n### Reviewer focus\\n" + focus.join("\\n") : "") + "\\n\\n*Evidence is heuristic, not a merge approval. It does not execute PR code.*";
}
async function api(path, options = {}) { const response = await fetch("https://api.github.com/repos/" + process.env.GITHUB_REPOSITORY + path, { ...options, headers: { Accept: "application/vnd.github+json", Authorization: "Bearer " + process.env.INPUT_GITHUB_TOKEN, "X-GitHub-Api-Version": "2022-11-28", ...(options.headers || {}) } }); if (!response.ok) throw new Error("GitHub API " + response.status + ": " + await response.text()); return response.status === 204 ? null : response.json(); }
async function main() { const event = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, "utf8")); if (!event.pull_request) throw new Error("MergeProof only runs on pull_request events."); const number = event.pull_request.number, body = brief(criteria(event.pull_request.body), await api("/pulls/" + number + "/files?per_page=100")); const comments = await api("/issues/" + number + "/comments?per_page=100"), existing = comments.find((c) => c.user.type === "Bot" && c.body.includes(marker)); await api(existing ? "/issues/comments/" + existing.id : "/issues/" + number + "/comments", { method: existing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }); if (process.env.INPUT_FAIL_ON_UNPROVEN === "true" && /\\*\\*(Unproven|Needs test|Needs spec:)/.test(body)) process.exitCode = 1; }
main().catch((error) => { console.error("MergeProof failed: " + error.message); process.exitCode = 1; });
