const fs = require("node:fs");
const marker = "<!-- mergeproof-comment -->";
const risks = [["Authentication",["auth","login","session","oauth","jwt","password"]],["Permissions",["permission","role","rbac","acl","authorize"]],["Payments",["payment","invoice","billing","stripe","checkout","webhook"]],["Database",["migration","schema","database","sql"]],["Environment",[".env","environment","config","secret","credential","token"]]];
function tokens(value) { let output = ""; for (const character of value.toLowerCase()) { const code = character.charCodeAt(0); output += ((code >= 97 && code <= 122) || (code >= 48 && code <= 57)) ? character : " "; } return output.split(" ").filter((word) => word.length > 2); }
function isTest(name) { const value = name.toLowerCase(); return value.includes("/test/") || value.includes("/tests/") || value.includes("/__tests__/") || value.includes(".test.") || value.includes(".spec."); }
function criteriaFrom(body = "") { const result = []; let active = false; for (const line of body.split("\n")) { const item = line.trim(), lower = item.toLowerCase(); if (lower.startsWith("#")) { if (lower.includes("acceptance criteria")) { active = true; continue; } if (active) break; } if (active && (item.startsWith("- [ ]") || lower.startsWith("- [x]"))) result.push(item.slice(item.indexOf("]") + 1).trim()); } return result; }
function matches(criterion, files, tests) { const wanted = new Set(tokens(criterion)); return files.filter((file) => isTest(file.filename) === tests).map((file) => ({ name:file.filename, score:tokens(file.filename).filter((word) => wanted.has(word)).length })).filter((file) => file.score).sort((a,b) => b.score-a.score).slice(0,2).map((file) => file.name); }
function brief(criteria, files) { if (!criteria.length) return marker + "\n## MergeProof — Evidence Gate\n\n**Needs spec:** add an ## Acceptance criteria section with Markdown checkboxes."; const rows = criteria.map((criterion) => { const implementation = matches(criterion, files, false), tests = matches(criterion, files, true), verdict = !implementation.length ? "Unproven" : !tests.length ? "Needs test" : "Proven"; return { criterion, verdict, text:"| " + criterion.replaceAll("|","\\|") + " | " + (implementation.join(", ") || "—") + " | " + (tests.join(", ") || "—") + " | **" + verdict + "** |" }; }); const names = files.map((file) => file.filename.toLowerCase()); const flags = risks.filter((item) => names.some((name) => item[1].some((word) => name.includes(word)))).map((item) => item[0] + " path changed"); if (files.some((file) => !isTest(file.filename)) && !files.some((file) => isTest(file.filename))) flags.push("Application code changed without a changed test file"); const focus = rows.filter((row) => row.verdict !== "Proven").map((row,index) => (index + 1) + ". Verify: " + row.criterion); return marker + "\n## MergeProof — Evidence Gate\n\n| Acceptance criterion | Implementation evidence | Test evidence | Verdict |\n| --- | --- | --- | --- |\n" + rows.map((row) => row.text).join("\n") + (flags.length ? "\n\n### Risk flags\n" + flags.map((flag) => "- " + flag).join("\n") : "") + (focus.length ? "\n\n### Reviewer focus\n" + focus.join("\n") : "") + "\n\nEvidence is heuristic, not a merge approval. It does not execute PR code."; }
async function api(path, options = {}) { const response = await fetch("https://api.github.com/repos/" + process.env.GITHUB_REPOSITORY + path, { ...options, headers:{Accept:"application/vnd.github+json",Authorization:"Bearer " + process.env.INPUT_GITHUB_TOKEN,"X-GitHub-Api-Version":"2022-11-28",...(options.headers || {})} }); if (!response.ok) throw new Error("GitHub API " + response.status + ": " + await response.text()); return response.status === 204 ? null : response.json(); }
async function main() { const event = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH,"utf8")); if (!event.pull_request) throw new Error("MergeProof only runs on pull_request events."); const number = event.pull_request.number, files = await api("/pulls/" + number + "/files?per_page=100"), body = brief(criteriaFrom(event.pull_request.body),files), comments = await api("/issues/" + number + "/comments?per_page=100"), existing = comments.find((comment) => comment.user.type === "Bot" && comment.body.includes(marker)); await api(existing ? "/issues/comments/" + existing.id : "/issues/" + number + "/comments",{method:existing ? "PATCH" : "POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})}); if (process.env.INPUT_FAIL_ON_UNPROVEN === "true" && (body.includes("**Unproven**") || body.includes("**Needs test**") || body.includes("**Needs spec:**"))) process.exitCode = 1; }
main().catch((error) => { console.error("MergeProof failed: " + error.message); process.exitCode = 1; });
