const proofRows = [
  ["Customer cannot view another account's invoice", "invoice-query.ts", "—", "Needs test"],
  ["Successful payment marks invoice paid", "stripe-webhook.ts", "stripe-webhook.test.ts", "Proven"],
  ["Failed payment preserves invoice status", "—", "—", "Unproven"],
];

export default function Home() {
  return (
    <main className="mx-auto max-w-6xl px-5 pb-24 pt-5 sm:px-8">
      <nav className="flex items-center justify-between py-4">
        <span className="text-sm font-extrabold tracking-[0.18em] text-slate-950">COPYMUSE <span className="text-violet-600">/ MERGEPROOF</span></span>
        <a className="rounded-full border border-violet-200 bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700" href="mailto:hello@copymuse.digital?subject=MergeProof%20private%20beta">Private beta</a>
      </nav>
      <section className="grid min-h-[620px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]">
        <div>
          <p className="mb-5 text-sm font-bold uppercase tracking-[0.16em] text-violet-600">Evidence gate for AI-assisted PRs</p>
          <h1 className="max-w-3xl text-5xl font-black tracking-[-0.065em] text-slate-950 sm:text-7xl">Know what you&apos;re <span className="text-violet-600">merging.</span></h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">MergeProof maps every acceptance criterion in a pull request to implementation and test evidence—so your team can ship AI-assisted code with a clear review trail.</p>
          <div className="mt-9 flex flex-wrap gap-3"><a className="rounded-lg bg-violet-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200 transition hover:-translate-y-0.5 hover:bg-violet-700" href="mailto:hello@copymuse.digital?subject=MergeProof%20private%20beta">Join private beta</a><a className="rounded-lg border border-slate-200 px-5 py-3 text-sm font-bold text-slate-700" href="#evidence">See the evidence gate</a></div>
        </div>
        <div className="rounded-2xl border border-slate-200 bg-slate-950 p-1 shadow-2xl shadow-violet-100"><div className="rounded-xl bg-[#121422] p-7 font-mono text-xs leading-6 text-slate-300"><p className="text-violet-300">## MergeProof — Evidence Gate</p><p className="mt-5 text-amber-300">⚠ Account isolation · invoice-query.ts · — · Needs test</p><p className="text-emerald-300">✓ Payment success · webhook.ts · webhook.test.ts · Proven</p><p className="mt-5 text-violet-300">Reviewer focus</p><p>1. Verify account scoping in the invoice query.</p><p>2. Add the failed-payment test before merge.</p></div></div>
      </section>
      <section className="border-t border-slate-200 py-20"><p className="text-sm font-bold uppercase tracking-[0.16em] text-violet-600">The problem</p><h2 className="mt-3 max-w-3xl text-3xl font-extrabold tracking-[-0.045em] text-slate-950 sm:text-5xl">AI writes faster. Review still needs proof.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Requirements get lost","Large diffs make it hard to see whether a PR fulfills the job it was opened to do."],["Tests can look convincing","A passing suite does not prove the important behavior—or its failure path—is covered."],["Review bots get noisy","MergeProof produces one focused brief instead of a wall of inline comments."]].map(([title, body], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="text-sm font-black text-violet-600">0{index + 1}</span><h3 className="mt-8 text-lg font-bold text-slate-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{body}</p></article>)}</div></section>
      <section id="evidence" className="border-t border-slate-200 py-20"><p className="text-sm font-bold uppercase tracking-[0.16em] text-violet-600">One brief. A human decision.</p><div className="mt-8 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><table className="w-full min-w-[690px] text-left text-sm"><thead className="border-b border-slate-200 text-slate-500"><tr><th className="pb-3">Acceptance criterion</th><th className="pb-3">Implementation</th><th className="pb-3">Test evidence</th><th className="pb-3">Verdict</th></tr></thead><tbody>{proofRows.map(([criterion, implementation, test, verdict]) => <tr key={criterion} className="border-b border-slate-100"><td className="py-4 font-medium text-slate-800">{criterion}</td><td className="py-4 font-mono text-xs text-violet-700">{implementation}</td><td className="py-4 font-mono text-xs text-slate-600">{test}</td><td className={`py-4 font-bold ${verdict === "Proven" ? "text-emerald-600" : "text-amber-600"}`}>{verdict}</td></tr>)}</tbody></table><div className="mt-7 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><b>Risk flags:</b> Payments path changed · Application code changed without a changed test file</div></div></section>
      <section className="border-t border-slate-200 py-20 text-center"><p className="text-sm font-bold uppercase tracking-[0.16em] text-violet-600">Rules first. AI optional.</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-extrabold tracking-[-0.045em] text-slate-950 sm:text-5xl">A GitHub Action, not another dashboard.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-slate-600">No source-code execution. No auto-approve. No secret access. Just an evidence brief that helps a human make a better merge decision.</p><a className="mt-8 inline-block rounded-lg bg-violet-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200" href="mailto:hello@copymuse.digital?subject=MergeProof%20private%20beta">Get private beta access</a></section>
    </main>
  );
}